name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build React App
      run: npm run build --if-present

    - name: Set up SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{secrets.SSH_PRIVATE_KEY}}
        known_hosts: '_'

    - name: Add known_hosts
      run: ssh-keyscan -H alwaysdata.net >> /home/kaa88/.ssh/known_hosts

    - name: Deploy
      run: rsync -rz --mkpath build/ kaa88@ssh-kaa88.alwaysdata.net:www/react_pro_skills
      # env:
      #   SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
